export const ADD_BET_TO_COUPON = "ADD_BET_TO_COUPON";
export const REMOVE_BET_FROM_COUPON = "REMOVE_BET_FROM_COUPON";
export const CLEAR_BETS_FROM_COUPON = "CLEARS_BETS_FROM_COUPON";

export const SET_TOKEN = "SET_TOKEN";
